-- Speed up the Tasks page for admins and managers.
--
-- The admin/manager variant of the /tasks query runs with an empty
-- `where` clause and `ORDER BY "dueDate" ASC`. Our existing Task
-- indexes all start with a discriminator column (assignedRole,
-- assignedUserId, kind, loanId, status) so none of them can satisfy
-- an ORDER BY dueDate when there is no filter on those columns.
-- Postgres therefore falls back to a sort of the entire Task table
-- on every admin render, which is exactly why the perf metric
-- `query.tasks.findMany.primary` was logging 10-18s durations and
-- saturating the connection pool.
--
-- A bare index on dueDate lets the planner do an index-ordered scan.
-- Idempotent so re-runs on already-migrated environments are safe.
CREATE INDEX IF NOT EXISTS "Task_dueDate_idx" ON "Task" ("dueDate");
