export const PAYROLL_LENDER_OPTIONS = [
  'UWM',
  'Button Finance',
  'Figure',
  'Kind Lending',
  'SunWest Mortgage',
  'EPM',
  'Spring EQ',
  '11 Mortgage',
  'Acra Lending',
  'AD Mortgage',
  'Ameritrust TPO',
  'AmWest Funding',
  'Angel Oak',
  'Arc Home',
  'Ardri',
  'Brokers Choice',
  'Brokers First Funding',
  'Cardinal Financial',
  'Carrington',
  'Champions Funding',
  'Change Wholesale',
  'Click N Close',
  'Deephaven Mortgage',
  'Emporium TPO',
  'Everstream Mortgage',
  'Finance of America Reverse',
  'First National Bank of America',
  'Forward Lending',
  'Foundation Mortgage',
  'Freedom Mortgage',
  'Fund Loans',
  'Giant Lending',
  'HomeBridge Wholesale',
  'HomeXpress Mortgage',
  'JMAC Lending',
  'Kiavi Hard Money',
  'LenderMAC',
  'LendingXpress',
  'Loan United',
  'LoanDepot',
  'LoanStream',
  'Logan Finance',
  'Longbridge Financial',
  'Luminate Bank',
  'Mutual Of Omaha',
  'Nations Direct Lending',
  'NewFi Wholesale',
  'NewRez',
  'NexBank Wholesale',
  'NFTYDoor',
  'OakTree Funding',
  'Open Wholesale',
  'Orion Lending',
  'PennyMac',
  'Plaza Home Mortgage',
  'PRMG',
  'REMN',
  'Smartfi Home Loans',
  'Splitero',
  'Symmetry Lending',
  'The Lender',
  'The Loan Store',
  'The Loan Store - FIGURE',
  'TMAC',
  'Triad Financial Services',
  'Val Chris',
  'Velocity Mortgage',
  'Village Capital',
  'Windsor Mortgage',
];
