-- Seeds the inactive Five9 new-lead push service. Admins must select the
-- allowed users and enable the service before it can dispatch.
INSERT INTO "IntegrationService" (
  "id",
  "slug",
  "name",
  "description",
  "type",
  "active",
  "config",
  "kind",
  "statusTrigger",
  "method",
  "urlTemplate",
  "bodyTemplate",
  "headersTemplate",
  "userScope",
  "userIds",
  "campaignScope",
  "campaignIds",
  "excludeSelected",
  "captureFields",
  "requiresBrandNew",
  "requiresNotBrandNew",
  "requiresAssignedUser",
  "requiresOAuth",
  "allowManualSend",
  "createdAt",
  "updatedAt"
) VALUES (
  gen_random_uuid(),
  'new-lead-push-five9',
  'New Lead Push - Five9',
  'Pushes newly assigned Lead Mailbox leads to the Five9 router middleware.',
  'five9',
  false,
  '{}'::jsonb,
  'SERVER',
  'ON_ASSIGN',
  'POST_JSON',
  'https://lead-router-fedfirst.onrender.com/webhooks/leadmailbox',
  '{
  "first_name": "{{lead.firstName}}",
  "last_name": "{{lead.lastName}}",
  "email": "{{lead.email}}",
  "number1": "{{lead.phone}}",
  "number2": "{{lead.homePhone}}",
  "number3": "{{lead.workPhone}}",

  "street": "{{lead.mailingAddress}}",
  "city": "{{lead.mailingCity}}",
  "state": "{{lead.mailingState}}",
  "zip": "{{lead.mailingZip}}",

  "property_value": "{{lead.propertyValue}}",
  "property_type": "{{lead.propertyType}}",
  "property_use": "{{lead.propertyUse}}",
  "property_ltv": "{{lead.propertyLtv}}",

  "loan_amount": "{{lead.loanAmount}}",
  "loan_rate": "{{lead.loanRate}}",
  "loan_term": "{{lead.loanTerm}}",
  "cash_out": "{{lead.cashOut}}",

  "credit_rating": "{{lead.creditRating}}",
  "current_balance": "{{lead.currentBalance}}",
  "current_payment": "{{lead.currentPayment}}",
  "current_rate": "{{lead.currentRate}}",

  "lead_id": "{{lead.vendorLeadId}}",
  "user_id": "{{user.id}}",
  "date_modified": "{{now.iso}}",

  "branch": "CA",
  "source": "LeadMailbox"
}',
  'User-Agent: FFL-Portal/1.0 (+lead-distribution)',
  'SPECIFIC',
  ARRAY[]::text[],
  'ANY',
  ARRAY[]::text[],
  false,
  '[]'::jsonb,
  true,
  false,
  true,
  false,
  false,
  NOW(),
  NOW()
)
ON CONFLICT ("slug") DO NOTHING;
